version: "3"

services:
  api:
    build: apiserver
    volumes:
      - ./configs/api:/home
    restart: always
    ports:
      - "8080:8080"
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
  s3:
    image: minio/minio
    volumes:
      - s3data:/data
      - ./configs/s3:/root/.minio
    ports:
      - "9199:9000"
    expose:
      - 9000
    command: server /data
volumes:
  dbdata:
  s3data:
