apiVersion: kfdef.apps.kubeflow.org/v1alpha1
kind: KfDef
metadata:
  creationTimestamp: null
  name: dataserver
  namespace: kubeflow
spec:
  appdir: /Users/kimsunho/Documents/dev/gorani-reader/backend/dataserver
  componentParams:
    ambassador:
    - name: ambassadorServiceType
      value: NodePort
  components:
  - ambassador
  - argo
  - centraldashboard
  - jupyter-web-app
  - katib
  - metacontroller
  - notebook-controller
  - pipeline
  - pytorch-operator
  - tensorboard
  - tf-job-operator
  packages:
  - argo
  - common
  - examples
  - gcp
  - jupyter
  - katib
  - metacontroller
  - modeldb
  - mpi-job
  - pipeline
  - pytorch-job
  - seldon
  - tensorboard
  - tf-serving
  - tf-training
  repo: /Users/kimsunho/Documents/dev/gorani-reader/backend/dataserver/.cache/v0.5.1/kubeflow
  useBasicAuth: false
  useIstio: false
  version: v0.5.1
status: {}
