cluster_threshold: 6.5
max_session_hours: 12
filter_wpm_threshold: 1000
cheat_eltime_threshold: 11
notify_topic_arn: "arn:aws:sns:ap-northeast-2:926877676119:notify-discord"
firebase_project_id: gorani-reader-249509
client_event_logs_s3_bucket: gorani-reader-client-event-logs
generated_review_s3_bucket: gorani-reader-generated-reviews
word2vec_k: 5
vocab_skills_s3_bucket: gorani-reader-vocab-skills
last_session_after_hours: 12
skip_session_hours: 0.1
firebase_cert:
  type: "service_account"
  project_id: "gorani-reader-249509"
  private_key_id: "3f7a2fa94e8715058ffbc563130f5b7a0e19ac55"
  private_key: "-----BEGIN PRIVATE KEY-----\nMIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCuqzdM00HuunOt\n4LORU14xioQ8txSEWbynE22g+2V1kJR2pEAuvBfvREbVzUH8axWM+VyeVsZ3it/r\nyvmKJE70WyyFDwRSw809k2KNscK11kJUWWmqWiC+AO8IF0QhCR92Tc3bWVcCnRxr\n/laJFxz9CaE40W5Kc0Tw/yVJdYFn90DmmikEH8kotDIga84KJle+pHGd6AVyCIIs\n0fRiTyJC5tzBmGyCaMGBEY7sOFh1ZhPQryHYJt65W9wzAKMx+OL0L7l1Mrs5Ogdc\nM/YX/1GjL75LqtdoG2VPq2I1x4bzPSR1Z3FZgQCz3HYQUTf+/3VXVu+F2UFQSLUb\nddEjxnOpAgMBAAECggEAB0avUMy358DOHiC1mKWLQrXCHcDED5Uoy4fyAbb/PYpZ\nv01HApT7MhBbNNkhhgLHwzESRElNAebspLpDMpeh6PV3iw2g8NN8J2cnzGT3ilLq\ncL0ulOlYvFMcu5UZu8uRJM2hOFSfw1NCpbAF/R0T0mmi7oakGS3CLszeI4UY1sXc\nUR4Dfx8r6kwczgTcUp4ke+VdwfaI8lTmU4wnJnYiZw/OXKCrBg3PI7pljS8X/Y3Y\n/BYxACBAOgMZDr7b43rWh2Z7u2IZORvZ/lT4f5HrYuuMRbU1zw6KhvpGrqHpiVJZ\n3+UFdJOrnmKWkxuc4xBsMqX3i/oFVhiT6Ku5LjfA5QKBgQDdMceBe6Vi0xDpeqwe\nZICH/R7d4jka+hQTEA46uIQLaQUG3agDlbUo2ukakq0PApJet46TGlXY5/yMF28t\n9C//nywKIxCudbNnXwc6lFeH+7ty96CNGtF8+IRSwCI5DcdzCVSqgoCvbH99eoG+\nUcDzVbw0uu0/4PP5zxGXdEVGdQKBgQDKJ0bwUwlGgb7ElihqTPUeTL04doEX/P0D\napsfXu2HtH/dqS3lP8LPrz7o7/Llpxw3jwvyqGAmbiVjfHJDBMAnBGhUw7N70iuu\nRsw/nFDJRUgxwtK3FsUoP5jRZqb4vVJ5E1G+evZgz7qwkb3wyXuCce1Ee29jHpLs\nxuLu+pkZ5QKBgQDWDzmSjlVEaRxhxyzQkNRuRkBb3HUFLWTF+fC7VRu8axrJRTM2\nnOffrNKPu8is0QFTlnHs3DyeGAuoi3k10K2uxJx7Buo6238OF8HIKAz5dV03ans+\ncuiu91YfOv8jlbkiE7KS/I6KtgY/KZJr23ROSPdFVG0LN6kEZScSGhx8jQKBgQDA\noNavEGDpR57xkqgmSvjTi4pPMFTo99Bcngv8w6cRxgSFwr0SE0TeQ/5tVqAdB7US\nmANpkdo1JIYKG76BcBht1XxZMTZpSacH5TyhbKFqeNNHX38Mqezq4lcLSobWxQi+\niJM/L8pwC+G4eNgGhudjMI5H0Fselzan2wjJcg/LpQKBgQCLf8gPl/pV0d7p77La\nCR//SacR4ozUI6JRAFLMSLciKo7go4J0KAmkTKcg9hScmFoq+NxPn6jaAW1Pu/JX\nJZpqaKO+GIsqqI7sVYBeHb+bMQoiWv5eAjDElI1HJKuSgyWA8ck+sbUdDfsENUJT\nlDPvFFEHZmymANMYZlh9MYI1LA==\n-----END PRIVATE KEY-----\n"
  client_email: "firebase-adminsdk-9t18s@gorani-reader-249509.iam.gserviceaccount.com"
  client_id: "116132035320841593768"
  auth_uri: "https://accounts.google.com/o/oauth2/auth"
  token_uri: "https://oauth2.googleapis.com/token"
  auth_provider_x509_cert_url: "https://www.googleapis.com/oauth2/v1/certs"
  client_x509_cert_url: "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-9t18s%40gorani-reader-249509.iam.gserviceaccount.com"

