apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-notebook
  labels:
    app: jupyter-notebook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter-notebook
  template:
    metadata:
      labels:
        app: jupyter-notebook
    spec:
      containers:
      - name: jupyter
        command: ["jupyter"]
        args: ["notebook", "--ip=0.0.0.0", "--allow-root"]
        image: ksunhokim/gorani-jupyter:v101
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: jupyter-notebook
spec:
  selector:
    app: jupyter-notebook 
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8888
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jupyter
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - etl.sunho.kim
    secretName: etl-sunho-kim-crt
  rules:
  - host: etl.sunho.kim
    http:
      paths:
      - path: /
        backend:
          serviceName: jupyter-notebook
          servicePort: 80
