apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
spec:
  template:
    spec:
      containers:
      - name: migreate
        image: ksunhokim/gorani-migrate:v5
        command: ["cqlsh",  "-f", "./migrations/schema.cql", "cassandra"]
      restartPolicy: Never
  backoffLimit: 0
