apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: train-
spec:
  entrypoint: dag
  arguments:
    parameters:
    - name: user_id
  templates:
$jupyter
  - name: dag
    dag:
      tasks:
      - name: train-time-model
        template: tf
        arguments:
          parameters: [{name: notebook, value: train-time-model}, {name: args, value: '{"user_id": {{workflow.parameters.user_id}}}'}]