apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: update-
spec:
  entrypoint: dag
  serviceAccountName: spark
  templates:
$jupyter
  - name: dag
    dag:
      tasks:
      - name: compute-auwpp
        template: jupyter
        arguments:
          parameters: [{name: notebook, value: compute-auwpp}, {name: args, value: '{}'}]
      - name: predict-time
        template: tf
        arguments:
          parameters: [{name: notebook, value: predict-time}, {name: args, value: '{}'}]
      - name: classify-readable-books
        dependencies: [compute-auwpp, predict-time]
        template: jupyter
        arguments:
          parameters: [{name: notebook, value: classify-readable-books}, {name: args, value: '{}'}]
      - name: compute-initial-books
        dependencies: [compute-auwpp, predict-time]
        template: jupyter
        arguments:
          parameters: [{name: notebook, value: compute-initial-books}, {name: args, value: '{}'}]
      - name: recommend-books
        dependencies: [compute-initial-books, classify-readable-books]
        template: jupyter
        arguments:
          parameters: [{name: notebook, value: recommend-books}, {name: args, value: '{}'}]
      - name: feed-posts
        dependencies: [classify-readable-books]
        template: jupyter
        arguments:
          parameters: [{name: notebook, value: feed-posts}, {name: args, value: '{}'}]