auth:
  secret: "12345678901234"
  admin_token: admintoken
db:
  environment: development
google:
  key: your key
  secret: your secret
s3:
  endpoint: s3
  key: 36J9X8EZI4KEV1G7EHXA
  secret: ECk2uqOoNqvtJIMQ3WYugvmNPL_-zm3WcRqP5vUM
  region: ap-southeast-2
  bucket: gorani
  https: false
  use_subpath: true
  set_policy: true
