auth:
  secret: "1234567890123412"
  admin_token: admintoken
db:
  environment: development
google:
  key: 707156763693-3mjdmcu9180togpbgc067es5hiq4ve3n.apps.googleusercontent.com
  secret: CVT2sD1iXNneIXqQPT_pFkbT
s3:
  endpoint: s3:9000
  key: 36J9X8EZI4KEV1G7EHXA
  secret: ECk2uqOoNqvtJIMQ3WYugvmNPL_-zm3WcRqP5vUM
  region: ap-southeast-2
  bucket: gorani
  https: false
  use_subpath: true
  set_policy: true
