// Code generated by protoc-gen-go. DO NOT EDIT.
// source: etl.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_etl_930a404581969f76, []int{0}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Word struct {
	Id                   int32         `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Word                 string        `protobuf:"bytes,2,opt,name=word,proto3" json:"word,omitempty"`
	Pronunciation        string        `protobuf:"bytes,3,opt,name=pronunciation,proto3" json:"pronunciation,omitempty"`
	Definitions          []*Definition `protobuf:"bytes,4,rep,name=definitions,proto3" json:"definitions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Word) Reset()         { *m = Word{} }
func (m *Word) String() string { return proto.CompactTextString(m) }
func (*Word) ProtoMessage()    {}
func (*Word) Descriptor() ([]byte, []int) {
	return fileDescriptor_etl_930a404581969f76, []int{1}
}
func (m *Word) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Word.Unmarshal(m, b)
}
func (m *Word) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Word.Marshal(b, m, deterministic)
}
func (dst *Word) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Word.Merge(dst, src)
}
func (m *Word) XXX_Size() int {
	return xxx_messageInfo_Word.Size(m)
}
func (m *Word) XXX_DiscardUnknown() {
	xxx_messageInfo_Word.DiscardUnknown(m)
}

var xxx_messageInfo_Word proto.InternalMessageInfo

func (m *Word) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Word) GetWord() string {
	if m != nil {
		return m.Word
	}
	return ""
}

func (m *Word) GetPronunciation() string {
	if m != nil {
		return m.Pronunciation
	}
	return ""
}

func (m *Word) GetDefinitions() []*Definition {
	if m != nil {
		return m.Definitions
	}
	return nil
}

type Definition struct {
	Id                   int32      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	WordId               int32      `protobuf:"varint,2,opt,name=word_id,json=wordId,proto3" json:"word_id,omitempty"`
	Definition           string     `protobuf:"bytes,3,opt,name=definition,proto3" json:"definition,omitempty"`
	Pos                  string     `protobuf:"bytes,4,opt,name=pos,proto3" json:"pos,omitempty"`
	Examples             []*Example `protobuf:"bytes,5,rep,name=examples,proto3" json:"examples,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Definition) Reset()         { *m = Definition{} }
func (m *Definition) String() string { return proto.CompactTextString(m) }
func (*Definition) ProtoMessage()    {}
func (*Definition) Descriptor() ([]byte, []int) {
	return fileDescriptor_etl_930a404581969f76, []int{2}
}
func (m *Definition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Definition.Unmarshal(m, b)
}
func (m *Definition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Definition.Marshal(b, m, deterministic)
}
func (dst *Definition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Definition.Merge(dst, src)
}
func (m *Definition) XXX_Size() int {
	return xxx_messageInfo_Definition.Size(m)
}
func (m *Definition) XXX_DiscardUnknown() {
	xxx_messageInfo_Definition.DiscardUnknown(m)
}

var xxx_messageInfo_Definition proto.InternalMessageInfo

func (m *Definition) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Definition) GetWordId() int32 {
	if m != nil {
		return m.WordId
	}
	return 0
}

func (m *Definition) GetDefinition() string {
	if m != nil {
		return m.Definition
	}
	return ""
}

func (m *Definition) GetPos() string {
	if m != nil {
		return m.Pos
	}
	return ""
}

func (m *Definition) GetExamples() []*Example {
	if m != nil {
		return m.Examples
	}
	return nil
}

type Example struct {
	DefinitionId         int32    `protobuf:"varint,1,opt,name=definition_id,json=definitionId,proto3" json:"definition_id,omitempty"`
	Foreign              string   `protobuf:"bytes,2,opt,name=foreign,proto3" json:"foreign,omitempty"`
	Native               string   `protobuf:"bytes,3,opt,name=native,proto3" json:"native,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Example) Reset()         { *m = Example{} }
func (m *Example) String() string { return proto.CompactTextString(m) }
func (*Example) ProtoMessage()    {}
func (*Example) Descriptor() ([]byte, []int) {
	return fileDescriptor_etl_930a404581969f76, []int{3}
}
func (m *Example) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Example.Unmarshal(m, b)
}
func (m *Example) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Example.Marshal(b, m, deterministic)
}
func (dst *Example) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Example.Merge(dst, src)
}
func (m *Example) XXX_Size() int {
	return xxx_messageInfo_Example.Size(m)
}
func (m *Example) XXX_DiscardUnknown() {
	xxx_messageInfo_Example.DiscardUnknown(m)
}

var xxx_messageInfo_Example proto.InternalMessageInfo

func (m *Example) GetDefinitionId() int32 {
	if m != nil {
		return m.DefinitionId
	}
	return 0
}

func (m *Example) GetForeign() string {
	if m != nil {
		return m.Foreign
	}
	return ""
}

func (m *Example) GetNative() string {
	if m != nil {
		return m.Native
	}
	return ""
}

type AddWordRequest struct {
	Word                 *Word    `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddWordRequest) Reset()         { *m = AddWordRequest{} }
func (m *AddWordRequest) String() string { return proto.CompactTextString(m) }
func (*AddWordRequest) ProtoMessage()    {}
func (*AddWordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_etl_930a404581969f76, []int{4}
}
func (m *AddWordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddWordRequest.Unmarshal(m, b)
}
func (m *AddWordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddWordRequest.Marshal(b, m, deterministic)
}
func (dst *AddWordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddWordRequest.Merge(dst, src)
}
func (m *AddWordRequest) XXX_Size() int {
	return xxx_messageInfo_AddWordRequest.Size(m)
}
func (m *AddWordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddWordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddWordRequest proto.InternalMessageInfo

func (m *AddWordRequest) GetWord() *Word {
	if m != nil {
		return m.Word
	}
	return nil
}

type GetWordsResponse struct {
	Words                []*Word  `protobuf:"bytes,1,rep,name=words,proto3" json:"words,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetWordsResponse) Reset()         { *m = GetWordsResponse{} }
func (m *GetWordsResponse) String() string { return proto.CompactTextString(m) }
func (*GetWordsResponse) ProtoMessage()    {}
func (*GetWordsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_etl_930a404581969f76, []int{5}
}
func (m *GetWordsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWordsResponse.Unmarshal(m, b)
}
func (m *GetWordsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWordsResponse.Marshal(b, m, deterministic)
}
func (dst *GetWordsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWordsResponse.Merge(dst, src)
}
func (m *GetWordsResponse) XXX_Size() int {
	return xxx_messageInfo_GetWordsResponse.Size(m)
}
func (m *GetWordsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWordsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetWordsResponse proto.InternalMessageInfo

func (m *GetWordsResponse) GetWords() []*Word {
	if m != nil {
		return m.Words
	}
	return nil
}

type GetWordByIdRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetWordByIdRequest) Reset()         { *m = GetWordByIdRequest{} }
func (m *GetWordByIdRequest) String() string { return proto.CompactTextString(m) }
func (*GetWordByIdRequest) ProtoMessage()    {}
func (*GetWordByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_etl_930a404581969f76, []int{6}
}
func (m *GetWordByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWordByIdRequest.Unmarshal(m, b)
}
func (m *GetWordByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWordByIdRequest.Marshal(b, m, deterministic)
}
func (dst *GetWordByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWordByIdRequest.Merge(dst, src)
}
func (m *GetWordByIdRequest) XXX_Size() int {
	return xxx_messageInfo_GetWordByIdRequest.Size(m)
}
func (m *GetWordByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWordByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetWordByIdRequest proto.InternalMessageInfo

func (m *GetWordByIdRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetWordByWordRequest struct {
	Word                 string   `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetWordByWordRequest) Reset()         { *m = GetWordByWordRequest{} }
func (m *GetWordByWordRequest) String() string { return proto.CompactTextString(m) }
func (*GetWordByWordRequest) ProtoMessage()    {}
func (*GetWordByWordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_etl_930a404581969f76, []int{7}
}
func (m *GetWordByWordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWordByWordRequest.Unmarshal(m, b)
}
func (m *GetWordByWordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWordByWordRequest.Marshal(b, m, deterministic)
}
func (dst *GetWordByWordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWordByWordRequest.Merge(dst, src)
}
func (m *GetWordByWordRequest) XXX_Size() int {
	return xxx_messageInfo_GetWordByWordRequest.Size(m)
}
func (m *GetWordByWordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWordByWordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetWordByWordRequest proto.InternalMessageInfo

func (m *GetWordByWordRequest) GetWord() string {
	if m != nil {
		return m.Word
	}
	return ""
}

type GetWordResponse struct {
	Word                 *Word    `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetWordResponse) Reset()         { *m = GetWordResponse{} }
func (m *GetWordResponse) String() string { return proto.CompactTextString(m) }
func (*GetWordResponse) ProtoMessage()    {}
func (*GetWordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_etl_930a404581969f76, []int{8}
}
func (m *GetWordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWordResponse.Unmarshal(m, b)
}
func (m *GetWordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWordResponse.Marshal(b, m, deterministic)
}
func (dst *GetWordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWordResponse.Merge(dst, src)
}
func (m *GetWordResponse) XXX_Size() int {
	return xxx_messageInfo_GetWordResponse.Size(m)
}
func (m *GetWordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetWordResponse proto.InternalMessageInfo

func (m *GetWordResponse) GetWord() *Word {
	if m != nil {
		return m.Word
	}
	return nil
}

type DeleteWordRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteWordRequest) Reset()         { *m = DeleteWordRequest{} }
func (m *DeleteWordRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteWordRequest) ProtoMessage()    {}
func (*DeleteWordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_etl_930a404581969f76, []int{9}
}
func (m *DeleteWordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteWordRequest.Unmarshal(m, b)
}
func (m *DeleteWordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteWordRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteWordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteWordRequest.Merge(dst, src)
}
func (m *DeleteWordRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteWordRequest.Size(m)
}
func (m *DeleteWordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteWordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteWordRequest proto.InternalMessageInfo

func (m *DeleteWordRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type BuildSqliteResponse struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuildSqliteResponse) Reset()         { *m = BuildSqliteResponse{} }
func (m *BuildSqliteResponse) String() string { return proto.CompactTextString(m) }
func (*BuildSqliteResponse) ProtoMessage()    {}
func (*BuildSqliteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_etl_930a404581969f76, []int{10}
}
func (m *BuildSqliteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildSqliteResponse.Unmarshal(m, b)
}
func (m *BuildSqliteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildSqliteResponse.Marshal(b, m, deterministic)
}
func (dst *BuildSqliteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildSqliteResponse.Merge(dst, src)
}
func (m *BuildSqliteResponse) XXX_Size() int {
	return xxx_messageInfo_BuildSqliteResponse.Size(m)
}
func (m *BuildSqliteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildSqliteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BuildSqliteResponse proto.InternalMessageInfo

func (m *BuildSqliteResponse) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type InsepectIsbnRequest struct {
	Isbn                 string   `protobuf:"bytes,1,opt,name=isbn,proto3" json:"isbn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InsepectIsbnRequest) Reset()         { *m = InsepectIsbnRequest{} }
func (m *InsepectIsbnRequest) String() string { return proto.CompactTextString(m) }
func (*InsepectIsbnRequest) ProtoMessage()    {}
func (*InsepectIsbnRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_etl_930a404581969f76, []int{11}
}
func (m *InsepectIsbnRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsepectIsbnRequest.Unmarshal(m, b)
}
func (m *InsepectIsbnRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsepectIsbnRequest.Marshal(b, m, deterministic)
}
func (dst *InsepectIsbnRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsepectIsbnRequest.Merge(dst, src)
}
func (m *InsepectIsbnRequest) XXX_Size() int {
	return xxx_messageInfo_InsepectIsbnRequest.Size(m)
}
func (m *InsepectIsbnRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InsepectIsbnRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InsepectIsbnRequest proto.InternalMessageInfo

func (m *InsepectIsbnRequest) GetIsbn() string {
	if m != nil {
		return m.Isbn
	}
	return ""
}

type InsepectIsbnResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InsepectIsbnResponse) Reset()         { *m = InsepectIsbnResponse{} }
func (m *InsepectIsbnResponse) String() string { return proto.CompactTextString(m) }
func (*InsepectIsbnResponse) ProtoMessage()    {}
func (*InsepectIsbnResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_etl_930a404581969f76, []int{12}
}
func (m *InsepectIsbnResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsepectIsbnResponse.Unmarshal(m, b)
}
func (m *InsepectIsbnResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsepectIsbnResponse.Marshal(b, m, deterministic)
}
func (dst *InsepectIsbnResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsepectIsbnResponse.Merge(dst, src)
}
func (m *InsepectIsbnResponse) XXX_Size() int {
	return xxx_messageInfo_InsepectIsbnResponse.Size(m)
}
func (m *InsepectIsbnResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InsepectIsbnResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InsepectIsbnResponse proto.InternalMessageInfo

type AddBookRequest struct {
	Isbn                 string   `protobuf:"bytes,1,opt,name=isbn,proto3" json:"isbn,omitempty"`
	RedisKey             string   `protobuf:"bytes,2,opt,name=redis_key,json=redisKey,proto3" json:"redis_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddBookRequest) Reset()         { *m = AddBookRequest{} }
func (m *AddBookRequest) String() string { return proto.CompactTextString(m) }
func (*AddBookRequest) ProtoMessage()    {}
func (*AddBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_etl_930a404581969f76, []int{13}
}
func (m *AddBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddBookRequest.Unmarshal(m, b)
}
func (m *AddBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddBookRequest.Marshal(b, m, deterministic)
}
func (dst *AddBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddBookRequest.Merge(dst, src)
}
func (m *AddBookRequest) XXX_Size() int {
	return xxx_messageInfo_AddBookRequest.Size(m)
}
func (m *AddBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddBookRequest proto.InternalMessageInfo

func (m *AddBookRequest) GetIsbn() string {
	if m != nil {
		return m.Isbn
	}
	return ""
}

func (m *AddBookRequest) GetRedisKey() string {
	if m != nil {
		return m.RedisKey
	}
	return ""
}

type CalculateRelevantWordsRequest struct {
	Reltype              string   `protobuf:"bytes,1,opt,name=reltype,proto3" json:"reltype,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CalculateRelevantWordsRequest) Reset()         { *m = CalculateRelevantWordsRequest{} }
func (m *CalculateRelevantWordsRequest) String() string { return proto.CompactTextString(m) }
func (*CalculateRelevantWordsRequest) ProtoMessage()    {}
func (*CalculateRelevantWordsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_etl_930a404581969f76, []int{14}
}
func (m *CalculateRelevantWordsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalculateRelevantWordsRequest.Unmarshal(m, b)
}
func (m *CalculateRelevantWordsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalculateRelevantWordsRequest.Marshal(b, m, deterministic)
}
func (dst *CalculateRelevantWordsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalculateRelevantWordsRequest.Merge(dst, src)
}
func (m *CalculateRelevantWordsRequest) XXX_Size() int {
	return xxx_messageInfo_CalculateRelevantWordsRequest.Size(m)
}
func (m *CalculateRelevantWordsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CalculateRelevantWordsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CalculateRelevantWordsRequest proto.InternalMessageInfo

func (m *CalculateRelevantWordsRequest) GetReltype() string {
	if m != nil {
		return m.Reltype
	}
	return ""
}

type RenewRecommenededBookRequest struct {
	UserLow              int32    `protobuf:"varint,1,opt,name=user_low,json=userLow,proto3" json:"user_low,omitempty"`
	UserHigh             int32    `protobuf:"varint,2,opt,name=user_high,json=userHigh,proto3" json:"user_high,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RenewRecommenededBookRequest) Reset()         { *m = RenewRecommenededBookRequest{} }
func (m *RenewRecommenededBookRequest) String() string { return proto.CompactTextString(m) }
func (*RenewRecommenededBookRequest) ProtoMessage()    {}
func (*RenewRecommenededBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_etl_930a404581969f76, []int{15}
}
func (m *RenewRecommenededBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RenewRecommenededBookRequest.Unmarshal(m, b)
}
func (m *RenewRecommenededBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RenewRecommenededBookRequest.Marshal(b, m, deterministic)
}
func (dst *RenewRecommenededBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RenewRecommenededBookRequest.Merge(dst, src)
}
func (m *RenewRecommenededBookRequest) XXX_Size() int {
	return xxx_messageInfo_RenewRecommenededBookRequest.Size(m)
}
func (m *RenewRecommenededBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RenewRecommenededBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RenewRecommenededBookRequest proto.InternalMessageInfo

func (m *RenewRecommenededBookRequest) GetUserLow() int32 {
	if m != nil {
		return m.UserLow
	}
	return 0
}

func (m *RenewRecommenededBookRequest) GetUserHigh() int32 {
	if m != nil {
		return m.UserHigh
	}
	return 0
}

type GetNeededQuizRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNeededQuizRequest) Reset()         { *m = GetNeededQuizRequest{} }
func (m *GetNeededQuizRequest) String() string { return proto.CompactTextString(m) }
func (*GetNeededQuizRequest) ProtoMessage()    {}
func (*GetNeededQuizRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_etl_930a404581969f76, []int{16}
}
func (m *GetNeededQuizRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNeededQuizRequest.Unmarshal(m, b)
}
func (m *GetNeededQuizRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNeededQuizRequest.Marshal(b, m, deterministic)
}
func (dst *GetNeededQuizRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNeededQuizRequest.Merge(dst, src)
}
func (m *GetNeededQuizRequest) XXX_Size() int {
	return xxx_messageInfo_GetNeededQuizRequest.Size(m)
}
func (m *GetNeededQuizRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNeededQuizRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetNeededQuizRequest proto.InternalMessageInfo

type GetNeededQuizResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNeededQuizResponse) Reset()         { *m = GetNeededQuizResponse{} }
func (m *GetNeededQuizResponse) String() string { return proto.CompactTextString(m) }
func (*GetNeededQuizResponse) ProtoMessage()    {}
func (*GetNeededQuizResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_etl_930a404581969f76, []int{17}
}
func (m *GetNeededQuizResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNeededQuizResponse.Unmarshal(m, b)
}
func (m *GetNeededQuizResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNeededQuizResponse.Marshal(b, m, deterministic)
}
func (dst *GetNeededQuizResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNeededQuizResponse.Merge(dst, src)
}
func (m *GetNeededQuizResponse) XXX_Size() int {
	return xxx_messageInfo_GetNeededQuizResponse.Size(m)
}
func (m *GetNeededQuizResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNeededQuizResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetNeededQuizResponse proto.InternalMessageInfo

type AnalyzeHtmlRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnalyzeHtmlRequest) Reset()         { *m = AnalyzeHtmlRequest{} }
func (m *AnalyzeHtmlRequest) String() string { return proto.CompactTextString(m) }
func (*AnalyzeHtmlRequest) ProtoMessage()    {}
func (*AnalyzeHtmlRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_etl_930a404581969f76, []int{18}
}
func (m *AnalyzeHtmlRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnalyzeHtmlRequest.Unmarshal(m, b)
}
func (m *AnalyzeHtmlRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnalyzeHtmlRequest.Marshal(b, m, deterministic)
}
func (dst *AnalyzeHtmlRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnalyzeHtmlRequest.Merge(dst, src)
}
func (m *AnalyzeHtmlRequest) XXX_Size() int {
	return xxx_messageInfo_AnalyzeHtmlRequest.Size(m)
}
func (m *AnalyzeHtmlRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AnalyzeHtmlRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AnalyzeHtmlRequest proto.InternalMessageInfo

type AnalyzeHtmlResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnalyzeHtmlResponse) Reset()         { *m = AnalyzeHtmlResponse{} }
func (m *AnalyzeHtmlResponse) String() string { return proto.CompactTextString(m) }
func (*AnalyzeHtmlResponse) ProtoMessage()    {}
func (*AnalyzeHtmlResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_etl_930a404581969f76, []int{19}
}
func (m *AnalyzeHtmlResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnalyzeHtmlResponse.Unmarshal(m, b)
}
func (m *AnalyzeHtmlResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnalyzeHtmlResponse.Marshal(b, m, deterministic)
}
func (dst *AnalyzeHtmlResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnalyzeHtmlResponse.Merge(dst, src)
}
func (m *AnalyzeHtmlResponse) XXX_Size() int {
	return xxx_messageInfo_AnalyzeHtmlResponse.Size(m)
}
func (m *AnalyzeHtmlResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AnalyzeHtmlResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AnalyzeHtmlResponse proto.InternalMessageInfo

type CreateSentencesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSentencesRequest) Reset()         { *m = CreateSentencesRequest{} }
func (m *CreateSentencesRequest) String() string { return proto.CompactTextString(m) }
func (*CreateSentencesRequest) ProtoMessage()    {}
func (*CreateSentencesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_etl_930a404581969f76, []int{20}
}
func (m *CreateSentencesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSentencesRequest.Unmarshal(m, b)
}
func (m *CreateSentencesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSentencesRequest.Marshal(b, m, deterministic)
}
func (dst *CreateSentencesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSentencesRequest.Merge(dst, src)
}
func (m *CreateSentencesRequest) XXX_Size() int {
	return xxx_messageInfo_CreateSentencesRequest.Size(m)
}
func (m *CreateSentencesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSentencesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSentencesRequest proto.InternalMessageInfo

type CreateSentencesResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSentencesResponse) Reset()         { *m = CreateSentencesResponse{} }
func (m *CreateSentencesResponse) String() string { return proto.CompactTextString(m) }
func (*CreateSentencesResponse) ProtoMessage()    {}
func (*CreateSentencesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_etl_930a404581969f76, []int{21}
}
func (m *CreateSentencesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSentencesResponse.Unmarshal(m, b)
}
func (m *CreateSentencesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSentencesResponse.Marshal(b, m, deterministic)
}
func (dst *CreateSentencesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSentencesResponse.Merge(dst, src)
}
func (m *CreateSentencesResponse) XXX_Size() int {
	return xxx_messageInfo_CreateSentencesResponse.Size(m)
}
func (m *CreateSentencesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSentencesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSentencesResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Empty)(nil), "pb.Empty")
	proto.RegisterType((*Word)(nil), "pb.Word")
	proto.RegisterType((*Definition)(nil), "pb.Definition")
	proto.RegisterType((*Example)(nil), "pb.Example")
	proto.RegisterType((*AddWordRequest)(nil), "pb.AddWordRequest")
	proto.RegisterType((*GetWordsResponse)(nil), "pb.GetWordsResponse")
	proto.RegisterType((*GetWordByIdRequest)(nil), "pb.GetWordByIdRequest")
	proto.RegisterType((*GetWordByWordRequest)(nil), "pb.GetWordByWordRequest")
	proto.RegisterType((*GetWordResponse)(nil), "pb.GetWordResponse")
	proto.RegisterType((*DeleteWordRequest)(nil), "pb.DeleteWordRequest")
	proto.RegisterType((*BuildSqliteResponse)(nil), "pb.BuildSqliteResponse")
	proto.RegisterType((*InsepectIsbnRequest)(nil), "pb.InsepectIsbnRequest")
	proto.RegisterType((*InsepectIsbnResponse)(nil), "pb.InsepectIsbnResponse")
	proto.RegisterType((*AddBookRequest)(nil), "pb.AddBookRequest")
	proto.RegisterType((*CalculateRelevantWordsRequest)(nil), "pb.CalculateRelevantWordsRequest")
	proto.RegisterType((*RenewRecommenededBookRequest)(nil), "pb.RenewRecommenededBookRequest")
	proto.RegisterType((*GetNeededQuizRequest)(nil), "pb.GetNeededQuizRequest")
	proto.RegisterType((*GetNeededQuizResponse)(nil), "pb.GetNeededQuizResponse")
	proto.RegisterType((*AnalyzeHtmlRequest)(nil), "pb.AnalyzeHtmlRequest")
	proto.RegisterType((*AnalyzeHtmlResponse)(nil), "pb.AnalyzeHtmlResponse")
	proto.RegisterType((*CreateSentencesRequest)(nil), "pb.CreateSentencesRequest")
	proto.RegisterType((*CreateSentencesResponse)(nil), "pb.CreateSentencesResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ETLServiceClient is the client API for ETLService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ETLServiceClient interface {
	GetWords(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetWordsResponse, error)
	AddWord(ctx context.Context, in *AddWordRequest, opts ...grpc.CallOption) (*Empty, error)
	GetWordById(ctx context.Context, in *GetWordByIdRequest, opts ...grpc.CallOption) (*Word, error)
	GetWordByWord(ctx context.Context, in *GetWordByWordRequest, opts ...grpc.CallOption) (*Word, error)
	DeleteWord(ctx context.Context, in *DeleteWordRequest, opts ...grpc.CallOption) (*Empty, error)
	BuildSqlite(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BuildSqliteResponse, error)
	InsepectIsbn(ctx context.Context, in *InsepectIsbnRequest, opts ...grpc.CallOption) (*InsepectIsbnResponse, error)
	AddBook(ctx context.Context, in *AddBookRequest, opts ...grpc.CallOption) (*Empty, error)
	CalculateRelevantWords(ctx context.Context, in *CalculateRelevantWordsRequest, opts ...grpc.CallOption) (*Empty, error)
}

type eTLServiceClient struct {
	cc *grpc.ClientConn
}

func NewETLServiceClient(cc *grpc.ClientConn) ETLServiceClient {
	return &eTLServiceClient{cc}
}

func (c *eTLServiceClient) GetWords(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetWordsResponse, error) {
	out := new(GetWordsResponse)
	err := c.cc.Invoke(ctx, "/pb.ETLService/GetWords", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eTLServiceClient) AddWord(ctx context.Context, in *AddWordRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/pb.ETLService/AddWord", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eTLServiceClient) GetWordById(ctx context.Context, in *GetWordByIdRequest, opts ...grpc.CallOption) (*Word, error) {
	out := new(Word)
	err := c.cc.Invoke(ctx, "/pb.ETLService/GetWordById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eTLServiceClient) GetWordByWord(ctx context.Context, in *GetWordByWordRequest, opts ...grpc.CallOption) (*Word, error) {
	out := new(Word)
	err := c.cc.Invoke(ctx, "/pb.ETLService/GetWordByWord", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eTLServiceClient) DeleteWord(ctx context.Context, in *DeleteWordRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/pb.ETLService/DeleteWord", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eTLServiceClient) BuildSqlite(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BuildSqliteResponse, error) {
	out := new(BuildSqliteResponse)
	err := c.cc.Invoke(ctx, "/pb.ETLService/BuildSqlite", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eTLServiceClient) InsepectIsbn(ctx context.Context, in *InsepectIsbnRequest, opts ...grpc.CallOption) (*InsepectIsbnResponse, error) {
	out := new(InsepectIsbnResponse)
	err := c.cc.Invoke(ctx, "/pb.ETLService/InsepectIsbn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eTLServiceClient) AddBook(ctx context.Context, in *AddBookRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/pb.ETLService/AddBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eTLServiceClient) CalculateRelevantWords(ctx context.Context, in *CalculateRelevantWordsRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/pb.ETLService/CalculateRelevantWords", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ETLServiceServer is the server API for ETLService service.
type ETLServiceServer interface {
	GetWords(context.Context, *Empty) (*GetWordsResponse, error)
	AddWord(context.Context, *AddWordRequest) (*Empty, error)
	GetWordById(context.Context, *GetWordByIdRequest) (*Word, error)
	GetWordByWord(context.Context, *GetWordByWordRequest) (*Word, error)
	DeleteWord(context.Context, *DeleteWordRequest) (*Empty, error)
	BuildSqlite(context.Context, *Empty) (*BuildSqliteResponse, error)
	InsepectIsbn(context.Context, *InsepectIsbnRequest) (*InsepectIsbnResponse, error)
	AddBook(context.Context, *AddBookRequest) (*Empty, error)
	CalculateRelevantWords(context.Context, *CalculateRelevantWordsRequest) (*Empty, error)
}

func RegisterETLServiceServer(s *grpc.Server, srv ETLServiceServer) {
	s.RegisterService(&_ETLService_serviceDesc, srv)
}

func _ETLService_GetWords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ETLServiceServer).GetWords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ETLService/GetWords",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ETLServiceServer).GetWords(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ETLService_AddWord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddWordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ETLServiceServer).AddWord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ETLService/AddWord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ETLServiceServer).AddWord(ctx, req.(*AddWordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ETLService_GetWordById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWordByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ETLServiceServer).GetWordById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ETLService/GetWordById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ETLServiceServer).GetWordById(ctx, req.(*GetWordByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ETLService_GetWordByWord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWordByWordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ETLServiceServer).GetWordByWord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ETLService/GetWordByWord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ETLServiceServer).GetWordByWord(ctx, req.(*GetWordByWordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ETLService_DeleteWord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteWordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ETLServiceServer).DeleteWord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ETLService/DeleteWord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ETLServiceServer).DeleteWord(ctx, req.(*DeleteWordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ETLService_BuildSqlite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ETLServiceServer).BuildSqlite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ETLService/BuildSqlite",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ETLServiceServer).BuildSqlite(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ETLService_InsepectIsbn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsepectIsbnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ETLServiceServer).InsepectIsbn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ETLService/InsepectIsbn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ETLServiceServer).InsepectIsbn(ctx, req.(*InsepectIsbnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ETLService_AddBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ETLServiceServer).AddBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ETLService/AddBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ETLServiceServer).AddBook(ctx, req.(*AddBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ETLService_CalculateRelevantWords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateRelevantWordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ETLServiceServer).CalculateRelevantWords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ETLService/CalculateRelevantWords",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ETLServiceServer).CalculateRelevantWords(ctx, req.(*CalculateRelevantWordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ETLService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ETLService",
	HandlerType: (*ETLServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetWords",
			Handler:    _ETLService_GetWords_Handler,
		},
		{
			MethodName: "AddWord",
			Handler:    _ETLService_AddWord_Handler,
		},
		{
			MethodName: "GetWordById",
			Handler:    _ETLService_GetWordById_Handler,
		},
		{
			MethodName: "GetWordByWord",
			Handler:    _ETLService_GetWordByWord_Handler,
		},
		{
			MethodName: "DeleteWord",
			Handler:    _ETLService_DeleteWord_Handler,
		},
		{
			MethodName: "BuildSqlite",
			Handler:    _ETLService_BuildSqlite_Handler,
		},
		{
			MethodName: "InsepectIsbn",
			Handler:    _ETLService_InsepectIsbn_Handler,
		},
		{
			MethodName: "AddBook",
			Handler:    _ETLService_AddBook_Handler,
		},
		{
			MethodName: "CalculateRelevantWords",
			Handler:    _ETLService_CalculateRelevantWords_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "etl.proto",
}

func init() { proto.RegisterFile("etl.proto", fileDescriptor_etl_930a404581969f76) }

var fileDescriptor_etl_930a404581969f76 = []byte{
	// 724 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x55, 0x5d, 0x4f, 0xdb, 0x4a,
	0x10, 0xcd, 0x07, 0x21, 0xc9, 0x04, 0xb8, 0xdc, 0x21, 0x24, 0x26, 0x97, 0x8b, 0xb8, 0x0b, 0x12,
	0x5c, 0xa4, 0xa6, 0x34, 0xa8, 0x0f, 0x7d, 0xe4, 0x4b, 0x10, 0x15, 0x55, 0xaa, 0xa9, 0xda, 0xc7,
	0xd4, 0x89, 0x07, 0x58, 0xe1, 0xac, 0x8d, 0xbd, 0x21, 0x0d, 0x8f, 0xfd, 0x05, 0xfd, 0xaf, 0xfd,
	0x03, 0xd5, 0x3a, 0x6b, 0x67, 0x1d, 0x10, 0x6f, 0x33, 0x67, 0x66, 0xce, 0x9e, 0x9d, 0x9c, 0x75,
	0xa0, 0x4a, 0xd2, 0x6b, 0x07, 0xa1, 0x2f, 0x7d, 0x2c, 0x04, 0x7d, 0x56, 0x86, 0xd2, 0xf9, 0x30,
	0x90, 0x13, 0xf6, 0x33, 0x0f, 0x0b, 0xdf, 0xfc, 0xd0, 0xc5, 0x15, 0x28, 0x70, 0xd7, 0xca, 0x6f,
	0xe7, 0xf7, 0x4b, 0x76, 0x81, 0xbb, 0x88, 0xb0, 0x30, 0xf6, 0x43, 0xd7, 0x2a, 0x6c, 0xe7, 0xf7,
	0xab, 0x76, 0x1c, 0xe3, 0x2e, 0x2c, 0x07, 0xa1, 0x2f, 0x46, 0x62, 0xc0, 0x1d, 0xc9, 0x7d, 0x61,
	0x15, 0xe3, 0x62, 0x16, 0xc4, 0x43, 0xa8, 0xb9, 0x74, 0xc3, 0x05, 0x57, 0x59, 0x64, 0x2d, 0x6c,
	0x17, 0xf7, 0x6b, 0x9d, 0x95, 0x76, 0xd0, 0x6f, 0x9f, 0xa5, 0xb0, 0x6d, 0xb6, 0xb0, 0x5f, 0x79,
	0x80, 0x59, 0xed, 0x99, 0x94, 0x26, 0x94, 0xd5, 0xf1, 0x3d, 0x3e, 0x55, 0x53, 0xb2, 0x17, 0x55,
	0xda, 0x75, 0x71, 0x0b, 0x60, 0x46, 0xa3, 0xc5, 0x18, 0x08, 0xae, 0x42, 0x31, 0xf0, 0x95, 0x02,
	0x55, 0x50, 0x21, 0xee, 0x41, 0x85, 0x7e, 0x38, 0xc3, 0xc0, 0xa3, 0xc8, 0x2a, 0xc5, 0xc2, 0x6a,
	0x4a, 0xd8, 0xf9, 0x14, 0xb3, 0xd3, 0x22, 0xfb, 0x0e, 0x65, 0x0d, 0xe2, 0x0e, 0x2c, 0xcf, 0x38,
	0x7b, 0xa9, 0xb2, 0xa5, 0x19, 0xd8, 0x75, 0xd1, 0x82, 0xf2, 0x8d, 0x1f, 0x12, 0xbf, 0x15, 0x7a,
	0x63, 0x49, 0x8a, 0x0d, 0x58, 0x14, 0x8e, 0xe4, 0x8f, 0xa4, 0x05, 0xea, 0x8c, 0xb5, 0x61, 0xe5,
	0xd8, 0x75, 0xd5, 0xee, 0x6d, 0x7a, 0x18, 0x51, 0x24, 0x71, 0x53, 0xaf, 0x5c, 0xf1, 0xd7, 0x3a,
	0x15, 0x25, 0x2c, 0x2e, 0xc7, 0x28, 0xeb, 0xc0, 0xea, 0x05, 0x49, 0x05, 0x44, 0x36, 0x45, 0x81,
	0x2f, 0x22, 0xc2, 0x2d, 0x28, 0xa9, 0x5a, 0x64, 0xe5, 0xe3, 0xbb, 0xcc, 0x46, 0xa6, 0x30, 0xdb,
	0x05, 0xd4, 0x33, 0x27, 0x93, 0x6e, 0x7a, 0xce, 0xdc, 0x7e, 0xd9, 0x01, 0xd4, 0xd3, 0x2e, 0x53,
	0x0f, 0x1a, 0x7a, 0xb4, 0x05, 0xd8, 0x5b, 0xf8, 0x4b, 0xf7, 0xa6, 0x22, 0x5e, 0x97, 0xbd, 0x03,
	0x7f, 0x9f, 0x91, 0x47, 0x92, 0x4c, 0xe6, 0x79, 0x05, 0x7b, 0xb0, 0x76, 0x32, 0xe2, 0x9e, 0x7b,
	0xfd, 0xe0, 0x71, 0x49, 0x29, 0xf3, 0x2a, 0x14, 0x47, 0xa1, 0xa7, 0xcf, 0x57, 0x21, 0xfb, 0x1f,
	0xd6, 0xba, 0x22, 0xa2, 0x80, 0x06, 0xb2, 0x1b, 0xf5, 0x85, 0xa1, 0x94, 0x47, 0x7d, 0x91, 0x28,
	0x55, 0x31, 0x6b, 0x40, 0x3d, 0xdb, 0x3a, 0x25, 0x65, 0xc7, 0xf1, 0xde, 0x4f, 0x7c, 0xff, 0xfe,
	0x95, 0x69, 0xfc, 0x07, 0xaa, 0x21, 0xb9, 0x3c, 0xea, 0xdd, 0xd3, 0x44, 0xff, 0xa2, 0x95, 0x18,
	0xf8, 0x48, 0x13, 0xf6, 0x01, 0xfe, 0x3d, 0x75, 0xbc, 0xc1, 0xc8, 0x73, 0x94, 0x58, 0x8f, 0x1e,
	0x1d, 0x91, 0xfc, 0x30, 0x53, 0x46, 0x0b, 0xca, 0x21, 0x79, 0x72, 0x12, 0x90, 0x26, 0x4d, 0x52,
	0xf6, 0x15, 0x36, 0x6d, 0x12, 0x34, 0xb6, 0x69, 0xe0, 0x0f, 0x87, 0x24, 0xc8, 0xa5, 0x8c, 0x96,
	0x0d, 0xa8, 0x8c, 0x22, 0x0a, 0x7b, 0x9e, 0x3f, 0xd6, 0xfb, 0x29, 0xab, 0xfc, 0xca, 0x1f, 0x2b,
	0x49, 0x71, 0xe9, 0x8e, 0xdf, 0xde, 0xe9, 0x87, 0x10, 0xf7, 0x5e, 0xf2, 0xdb, 0x3b, 0x75, 0xdb,
	0x0b, 0x92, 0x9f, 0x48, 0xf1, 0x7d, 0x1e, 0xf1, 0x27, 0xcd, 0xc7, 0x9a, 0xb0, 0x3e, 0x87, 0xeb,
	0x35, 0xd4, 0x01, 0x8f, 0x85, 0xe3, 0x4d, 0x9e, 0xe8, 0x52, 0x0e, 0xbd, 0xa4, 0x7d, 0x1d, 0xd6,
	0x32, 0xa8, 0x6e, 0xb6, 0xa0, 0x71, 0x1a, 0x92, 0x23, 0xe9, 0x9a, 0x84, 0x24, 0x31, 0xa0, 0xe4,
	0xa6, 0x6c, 0x03, 0x9a, 0xcf, 0x2a, 0xd3, 0xa1, 0xce, 0xef, 0x22, 0xc0, 0xf9, 0x97, 0xab, 0x6b,
	0x0a, 0x1f, 0xf9, 0x80, 0xf0, 0x0d, 0x54, 0x12, 0xff, 0x62, 0x35, 0x7e, 0x74, 0xea, 0x03, 0xd4,
	0xaa, 0xab, 0x70, 0xde, 0xd8, 0x2c, 0x87, 0x07, 0x50, 0xd6, 0xcf, 0x03, 0x51, 0xb5, 0x64, 0xdf,
	0x4a, 0x6b, 0xc6, 0xc0, 0x72, 0xf8, 0x0e, 0x6a, 0x86, 0xcd, 0xb1, 0x61, 0x50, 0x1a, 0xbe, 0x6f,
	0xa5, 0xd6, 0x64, 0x39, 0x7c, 0x0f, 0xcb, 0x19, 0xcf, 0xa3, 0x95, 0x19, 0x32, 0x8f, 0x32, 0xc7,
	0x0e, 0xd5, 0x87, 0x2a, 0x71, 0x33, 0xae, 0x4f, 0x3f, 0x6a, 0x73, 0xee, 0xce, 0x6a, 0x3b, 0x82,
	0x9a, 0x61, 0x6d, 0xf3, 0xe6, 0x4d, 0x15, 0xbe, 0x60, 0x7b, 0x96, 0xc3, 0x53, 0x58, 0x32, 0xbd,
	0x8b, 0x71, 0xeb, 0x0b, 0xc6, 0x6f, 0x59, 0xcf, 0x0b, 0x73, 0x1b, 0x54, 0xe6, 0x4a, 0x37, 0x68,
	0x38, 0x2d, 0xab, 0xf2, 0x12, 0x1a, 0x2f, 0x3b, 0x1a, 0xff, 0x53, 0x6d, 0xaf, 0xba, 0x3d, 0xc3,
	0xd4, 0x5f, 0x8c, 0xff, 0x64, 0x8e, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0x87, 0x1e, 0x11, 0xb4,
	0x71, 0x06, 0x00, 0x00,
}
